<?php
/**
 * Created by PhpStorm.
 * User: IvanMatas
 * Date: 13-Jun-16
 * Time: 3:40 PM
 */
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeRepository extends EntityRepository
{
}