<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectsRepository extends EntityRepository
{
}
